// <auto-generated />
using System;
using DigitalPrescriptionProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalPrescriptionProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalPrescriptionProject.Data.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speciality")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DoctorId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Age = 45,
                            Email = "john.smith@example.com",
                            FirstName = "John",
                            ImagePath = "/Images/DoctorsImage/doctor1.jpg",
                            LastName = "Smith",
                            Phone = "01711111111",
                            Speciality = 0
                        },
                        new
                        {
                            DoctorId = 2,
                            Age = 52,
                            Email = "sarah.williams@example.com",
                            FirstName = "Sarah",
                            ImagePath = "/Images/DoctorsImage/doctor2.jpg",
                            LastName = "Williams",
                            Phone = "01722222222",
                            Speciality = 2
                        },
                        new
                        {
                            DoctorId = 3,
                            Age = 48,
                            Email = "michael.brown@example.com",
                            FirstName = "Michael",
                            ImagePath = "/Images/DoctorsImage/doctor3.jpg",
                            LastName = "Brown",
                            Phone = "01733333333",
                            Speciality = 3
                        },
                        new
                        {
                            DoctorId = 4,
                            Age = 39,
                            Email = "emily.davis@example.com",
                            FirstName = "Emily",
                            ImagePath = "/Images/DoctorsImage/doctor4.jpg",
                            LastName = "Davis",
                            Phone = "01744444444",
                            Speciality = 4
                        },
                        new
                        {
                            DoctorId = 5,
                            Age = 42,
                            Email = "david.wilson@example.com",
                            FirstName = "David",
                            ImagePath = "/Images/DoctorsImage/doctor5.jpg",
                            LastName = "Wilson",
                            Phone = "01755555555",
                            Speciality = 5
                        },
                        new
                        {
                            DoctorId = 6,
                            Age = 44,
                            Email = "olivia.taylor@example.com",
                            FirstName = "Olivia",
                            ImagePath = "/Images/DoctorsImage/doctor6.jpg",
                            LastName = "Taylor",
                            Phone = "01766666666",
                            Speciality = 12
                        },
                        new
                        {
                            DoctorId = 7,
                            Age = 55,
                            Email = "robert.anderson@example.com",
                            FirstName = "Robert",
                            ImagePath = "/Images/DoctorsImage/doctor7.jpg",
                            LastName = "Anderson",
                            Phone = "01777777777",
                            Speciality = 7
                        },
                        new
                        {
                            DoctorId = 8,
                            Age = 41,
                            Email = "sophia.thomas@example.com",
                            FirstName = "Sophia",
                            ImagePath = "/Images/DoctorsImage/doctor8.jpg",
                            LastName = "Thomas",
                            Phone = "01788888888",
                            Speciality = 6
                        },
                        new
                        {
                            DoctorId = 9,
                            Age = 50,
                            Email = "daniel.moore@example.com",
                            FirstName = "Daniel",
                            ImagePath = "/Images/DoctorsImage/doctor9.jpg",
                            LastName = "Moore",
                            Phone = "01799999999",
                            Speciality = 9
                        },
                        new
                        {
                            DoctorId = 10,
                            Age = 37,
                            Email = "emma.martin@example.com",
                            FirstName = "Emma",
                            ImagePath = "/Images/DoctorsImage/doctor10.jpg",
                            LastName = "Martin",
                            Phone = "01811111111",
                            Speciality = 15
                        });
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Age = 35,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rahim.ahmed@example.com",
                            FirstName = "Rahim",
                            Gender = 0,
                            ImagePath = "/Images/PatientsImage/patient1.jpg",
                            LastName = "Ahmed",
                            Phone = "01811112222"
                        },
                        new
                        {
                            PatientId = 2,
                            Age = 28,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nusrat.jahan@example.com",
                            FirstName = "Nusrat",
                            Gender = 1,
                            ImagePath = "/Images/PatientsImage/patient2.jpg",
                            LastName = "Jahan",
                            Phone = "01822223333"
                        },
                        new
                        {
                            PatientId = 3,
                            Age = 52,
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karim.hossain@example.com",
                            FirstName = "Karim",
                            Gender = 0,
                            ImagePath = "/Images/PatientsImage/patient3.jpg",
                            LastName = "Hossain",
                            Phone = "01833334444"
                        },
                        new
                        {
                            PatientId = 4,
                            Age = 24,
                            CreatedAt = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mim.akter@example.com",
                            FirstName = "Mim",
                            Gender = 1,
                            ImagePath = "/Images/PatientsImage/patient4.jpg",
                            LastName = "Akter",
                            Phone = "01844445555"
                        },
                        new
                        {
                            PatientId = 5,
                            Age = 41,
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sakib.hasan@example.com",
                            FirstName = "Sakib",
                            Gender = 0,
                            ImagePath = "/Images/PatientsImage/patient5.jpg",
                            LastName = "Hasan",
                            Phone = "01855556666"
                        },
                        new
                        {
                            PatientId = 6,
                            Age = 31,
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sumaiya.rahman@example.com",
                            FirstName = "Sumaiya",
                            Gender = 1,
                            ImagePath = "/Images/PatientsImage/patient6.jpg",
                            LastName = "Rahman",
                            Phone = "01866667777"
                        },
                        new
                        {
                            PatientId = 7,
                            Age = 47,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "imran.kabir@example.com",
                            FirstName = "Imran",
                            Gender = 0,
                            ImagePath = "/Images/PatientsImage/patient7.jpg",
                            LastName = "Kabir",
                            Phone = "01877778888"
                        },
                        new
                        {
                            PatientId = 8,
                            Age = 19,
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ayesha.sultana@example.com",
                            FirstName = "Ayesha",
                            Gender = 1,
                            ImagePath = "/Images/PatientsImage/patient8.jpg",
                            LastName = "Sultana",
                            Phone = "01888889999"
                        },
                        new
                        {
                            PatientId = 9,
                            Age = 60,
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tanvir.islam@example.com",
                            FirstName = "Tanvir",
                            Gender = 0,
                            ImagePath = "/Images/PatientsImage/patient9.jpg",
                            LastName = "Islam",
                            Phone = "01911112222"
                        },
                        new
                        {
                            PatientId = 10,
                            Age = 26,
                            CreatedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fariha.chowdhury@example.com",
                            FirstName = "Fariha",
                            Gender = 1,
                            ImagePath = "/Images/PatientsImage/patient10.jpg",
                            LastName = "Chowdhury",
                            Phone = "01922223333"
                        },
                        new
                        {
                            PatientId = 11,
                            Age = 38,
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arif.mahmud@example.com",
                            FirstName = "Arif",
                            Gender = 0,
                            ImagePath = "/Images/PatientsImage/patient11.jpg",
                            LastName = "Mahmud",
                            Phone = "01933334444"
                        },
                        new
                        {
                            PatientId = 12,
                            Age = 33,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "raisa.islam@example.com",
                            FirstName = "Raisa",
                            Gender = 1,
                            ImagePath = "/Images/PatientsImage/patient12.jpg",
                            LastName = "Islam",
                            Phone = "01944445555"
                        });
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.PrescribedTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("TestName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescribedTests");
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<string>("ClinicalNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.PrescriptionItem", b =>
                {
                    b.Property<int>("PrescriptionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionItemId"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionItemId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.Doctor", b =>
                {
                    b.HasOne("DigitalPrescriptionProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.Patient", b =>
                {
                    b.HasOne("DigitalPrescriptionProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.PrescribedTest", b =>
                {
                    b.HasOne("DigitalPrescriptionProject.Models.Prescription", "Prescription")
                        .WithMany("PrescribedTests")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.Prescription", b =>
                {
                    b.HasOne("DigitalPrescriptionProject.Models.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalPrescriptionProject.Models.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.PrescriptionItem", b =>
                {
                    b.HasOne("DigitalPrescriptionProject.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DigitalPrescriptionProject.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DigitalPrescriptionProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DigitalPrescriptionProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DigitalPrescriptionProject.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalPrescriptionProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DigitalPrescriptionProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.Doctor", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.Patient", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("DigitalPrescriptionProject.Models.Prescription", b =>
                {
                    b.Navigation("PrescribedTests");

                    b.Navigation("PrescriptionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
